sudo: required
services:
  - docker

before_install:
  - docker build -t saadia45/docker-react -f Dockerfile.dev .

script:
  - docker run saadia45/docker-react npm run test -- --coverage
  - OR use the updated command below
  - docker run -e CI=true saadia45/docker-react npm run test